# Generated by Django 2.0 on 2017-12-14 09:31

from django.db import migrations, models
import ocd.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ocuser_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocuser',
            name='uid',
            field=models.CharField(default=ocd.utilities.create_uuid, max_length=32, unique=True),
        ),
    ]
