# Generated by Django 2.0 on 2017-12-06 12:47

from django.db import migrations, models
import django.db.models.deletion
import ocd.base_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=ocd.base_models.create_uid, max_length=24, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Public community')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='community_logo', verbose_name='Community logo')),
                ('official_identifier', models.CharField(blank=True, max_length=300, null=True, verbose_name='Community identifier')),
                ('upcoming_meeting_started', models.BooleanField(default=False, verbose_name='Meeting started')),
                ('upcoming_meeting_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Upcoming meeting title')),
                ('upcoming_meeting_scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Upcoming meeting scheduled at')),
                ('upcoming_meeting_location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Upcoming meeting location')),
                ('upcoming_meeting_comments', ocd.base_models.HTMLField(blank=True, null=True, verbose_name='Upcoming meeting background')),
                ('upcoming_meeting_guests', models.TextField(blank=True, help_text='Enter each guest in a separate line', null=True, verbose_name='Guests in upcoming meeting')),
                ('upcoming_meeting_version', models.IntegerField(default=0, verbose_name='Upcoming meeting version')),
                ('upcoming_meeting_is_published', models.BooleanField(default=False, verbose_name='Upcoming meeting is published')),
                ('upcoming_meeting_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Upcoming meeting published at')),
                ('upcoming_meeting_summary', ocd.base_models.HTMLField(blank=True, null=True, verbose_name='Upcoming meeting summary')),
                ('board_name', models.CharField(default='Board', max_length=200, verbose_name='Board name')),
                ('straw_voting_enabled', models.BooleanField(default=False, verbose_name='Straw voting enabled')),
                ('issue_ranking_enabled', models.BooleanField(default=False, verbose_name='Issue ranking votes enabled')),
                ('voting_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Straw Vote ends at')),
                ('referendum_started', models.BooleanField(default=False, verbose_name='Referendum started')),
                ('referendum_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Referendum started at')),
                ('referendum_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Referendum ends at')),
                ('default_quorum', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Default quorum')),
                ('allow_links_in_emails', models.BooleanField(default=True, verbose_name='Allow links inside emails')),
                ('email_invitees', models.BooleanField(default=False, verbose_name='Send mails to invitees')),
                ('register_missing_board_members', models.BooleanField(default=False, verbose_name='Register missing board members')),
                ('inform_system_manager', models.BooleanField(default=False, verbose_name='Inform System Manager')),
                ('no_meetings_community', models.BooleanField(default=False, verbose_name='Community without meetings?')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityConfidentialReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title to give this reason.', max_length=255, verbose_name='Name')),
                ('community', models.ForeignKey(help_text='A reason that can be used for marking items as confidential in your community.', on_delete=django.db.models.deletion.PROTECT, related_name='confidential_reasons', to='communities.Community')),
            ],
            options={
                'verbose_name': 'Confidential Reason',
                'verbose_name_plural': 'Confidential Reasons',
                'ordering': ['community'],
            },
        ),
    ]
