# Generated by Django 2.0 on 2017-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20171206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='issue_ranking_enabled',
            field=models.BooleanField(default=True, verbose_name='Issue ranking votes enabled'),
        ),
        migrations.AlterField(
            model_name='community',
            name='straw_voting_enabled',
            field=models.BooleanField(default=True, verbose_name='Straw voting enabled'),
        ),
    ]
