# Generated by Django 2.0 on 2017-12-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteresult',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='issues.Proposal'),
        ),
        migrations.AddField(
            model_name='proposalvoteboard',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.Proposal'),
        ),
    ]
