# Generated by Django 2.0 on 2017-12-13 18:23

import django.core.files.storage
from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20171206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage('/home/yaniv/projects/OpComm/uploads'), upload_to=issues.models.issue_attachment_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Task'), (2, 'Rule'), (3, 'General')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Con'), (0, 'Neutral'), (1, 'Pro')], default=0, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='proposalvoteargumentranking',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Con'), (1, 'Pro')], verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='proposalvoteboard',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Con'), (0, 'Neutral'), (1, 'Pro')], default=0, verbose_name='Vote'),
        ),
    ]
