# Generated by Django 2.0 on 2017-12-14 08:58

import django.core.files.storage
from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20171213_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage('/home/yaniv/Projects/OpComm/uploads'), upload_to=issues.models.issue_attachment_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'כללי')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'נגד'), (0, 'נמנע'), (1, 'בעד')], default=0, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='proposalvoteargumentranking',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'נגד'), (1, 'בעד')], verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='proposalvoteboard',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'נגד'), (0, 'נמנע'), (1, 'בעד')], default=0, verbose_name='Vote'),
        ),
    ]
