# Generated by Django 2.0 on 2017-12-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('issues', '0002_auto_20171206_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20171206_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingexternalparticipant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.Meeting', verbose_name='Meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda_items',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='meetings.AgendaItem', to='issues.Issue', verbose_name='Agenda items'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='communities.Community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='participated_in_meeting', through='meetings.MeetingParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_items', to='issues.Issue', verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='meetings.Meeting', verbose_name='Meeting'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user'), ('meeting', 'ordinal')},
        ),
        migrations.AlterUniqueTogether(
            name='agendaitem',
            unique_together={('meeting', 'issue')},
        ),
    ]
